pipeline {
    agent { label 'mvnserver' }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub
                git url: 'https://github.com/madhuri-bhamidipati/simple-java-maven-app.git', branch: 'master'
            }
        }

        stage('Build') {
            steps {
                // Go inside src folder where pom.xml is
                dir('src') {
                    sh '/usr/bin/mvn -B -DskipTests clean package -f pom.xml'
                }
            }
        }

        stage('Test') {
            steps {
                dir('src') {
                    sh '/usr/bin/mvn test'
                }
            }
        }

        stage('Deliver') {
            steps {
                echo 'Deliver stage placeholder'
            }
        }
    }
}

