pipeline {
    agent { label 'mvnserver' }  // your agent label
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh '/usr/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Skipping tests for now'
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver stage'
            }
        }
    }
}

