pipeline {
    agent { label 'mvnserver' }  // your agent label
    environment {
        MAVEN_HOME = '/opt/apache-maven-3.9.9'
        PATH = "${MAVEN_HOME}/bin:${env.PATH}" // prepend Maven bin to PATH
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Skipping tests for now'
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver stage'
            }
        }
    }
}
